import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>med.voll</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen bg-zinc-900 text-zinc-300">
        <h1 className="text-3xl">Hello World</h1>
      </div>
    </>
  );
}
